name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm test

#    - name: Run integration tests
#      run: npm run test:integration

    - name: Install Cypress
      run: npm install cypress

    - name: Run E2E tests with Cypress
      run: npx cypress run
